[custom.all.pact-api]
type = "local"
path = "api"
ipkg = "pact-api.ipkg"

[custom.all.pact-wai]
type = "local"
path = "wai"
ipkg = "pact-wai.ipkg"

[custom.all.pact-server]
type = "local"
path = "server"
ipkg = "pact-server.ipkg"

[custom.all.pact-client]
type = "local"
path = "client"
ipkg = "pact-client.ipkg"

[custom.all.pact-todomvc]
type = "local"
path = "todomvc"
ipkg = "pact-todomvc.ipkg"

[custom.all.pact-todomvc-client]
type = "local"
path = "todomvc"
ipkg = "pact-todomvc-client.ipkg"