[custom.all.pact-api]
type = "local"
path = "api"
ipkg = "pact-api.ipkg"
test = "test/test.ipkg"

[custom.all.pact-wai]
type = "local"
path = "wai"
ipkg = "pact-wai.ipkg"
test = "test/test.ipkg"

[custom.all.pact-server]
type = "local"
path = "server"
ipkg = "pact-server.ipkg"
test = "test/test.ipkg"

[custom.all.pact-todomvc]
type = "local"
path = "todomvc"
ipkg = "pact-todomvc.ipkg"