[custom.all.pact]
type = "local"
path = "."
ipkg = "pact.ipkg"
test = "test/test.ipkg"

[custom.all.sample]
type = "local"
path = "."
ipkg = "sample.ipkg"

[custom.all.pact-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.records]
type = "github"
url = "git@github.com:kuribas/idris-records.git"
commit = "main"
ipkg = "records.ipkg"